myapp/blog/urls.py
from django.urls import path
from . import views  # Ensure views is properly imported


app_name='blog'
urlpatterns = [
    path("", views.index, name="index"),  # Ensure this exists
    path("post/<int:post_id>", views.detail, name="detail"), 
    path("new_url", views.new_url_view, name="new_url_page"),
    path("old_url", views.old_url_view, name="old_url"),
]

myapp/myapp/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls import handler404
from .views import custom_404_view

handler404 = custom_404_view

urlpatterns = [
    path("blog/", include("blog.urls")),  # Ensure this matches 'blog/urls.py'
    path("admin/", admin.site.urls),
]

myapp/blog/models.py
from django.db import models

# Create your models here.

myapp/blog/views.py
from django.shortcuts import render,redirect,render
from django.http import HttpResponse
from django.urls import reverse
import logging
# Create your views here.
posts=[
        {'id':1,'title':'Post1','content':'Content of Post1'},
        {'id':2,'title':'Post2','content':'Content of Post2'},
        {'id':3,'title':'Post3','content':'Content of Post3'},
        {'id':4,'title':'Post4','content':'Content of Post4'},
]

def index(request):
    blog_title='Latest Posts'
    
    return render(request,'blog/index.html',{'blog_title':blog_title,'posts':posts})

def detail(request,post_id):
    post=next((item for item in posts if item['id']==post_id),None)
    logger=logging.getLogger("Testing")
    logger.debug(f'post variable is {post}')
    return render(request,'blog/detail.html',{'post':post})

def old_url_view(request):
    return redirect(reverse('blog:new_url_page'))

def new_url_view(request):
    return HttpResponse("Hello I am rukaa")

myapp/myapp/views.py
from django.shortcuts import render

def custom_404_view(request, exception):
    return render(request, '404.html', status=404)

myapp/blog/templates/blog/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{blog_title | default:'Document'}}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'blog/style.css' %}./style.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css">
</head>
<body >
    <!--HEader-->
    {%include 'blog/includes/header.html'%}
        {%block content%}

        {%endblock%}
    <!--Footer-->
    {%include 'blog/includes/footer.html'%}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>

myapp/blog/templates/blog/detail.html
{%extends 'blog/base.html'%}
{%block content%}
    <div class="container-fluid ">
       
        <div class="row">
            <div class="col-lg-8">
              <h1 class="mb-4">Post Title</h1>
              <p class="text-muted">Posted on January 1, 2024</p>
              <img src="https://via.placeholder.com/800x400" class="img-fluid mb-4" alt="Blog Image">
              <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla consectetur tortor vel magna tincidunt tempus. Maecenas eget maximus eros. Vivamus id nisl lacus. Donec et risus turpis. In nec efficitur purus, ac faucibus nulla. Aenean nec malesuada velit. Quisque ac mauris ac turpis semper interdum.</p>
              <p>Sed et lorem et lacus consequat suscipit. Vestibulum dapibus sapien et eros aliquam, a dictum leo vehicula. Aliquam consequat turpis vitae lectus tristique, quis efficitur orci fermentum. Phasellus a ligula pulvinar, blandit eros at, euismod nisl. Nam pharetra urna id purus volutpat, a feugiat magna convallis. Curabitur vestibulum velit sit amet nisl sollicitudin, eget rutrum enim fermentum.</p>
              <p>Donec quis nisi vitae metus sodales fermentum ac eu eros. Nulla facilisi. Fusce bibendum nisl et varius vehicula. Duis volutpat convallis justo nec pharetra. Cras convallis dolor vitae hendrerit mollis. Curabitur ultrices odio vitae sapien fringilla rhoncus. Ut feugiat condimentum ligula, vel faucibus neque sollicitudin sed. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nam eget mauris hendrerit, lobortis urna id, sollicitudin est. Nam semper aliquam magna, non egestas orci elementum ac.</p>
            </div>
            <div class="col-lg-4">
              <div class="card mt-3">
                <div class="card-body">
                  <h5 class="card-title">Related Posts</h5>
                  <ul class="list-unstyled">
                    <li><a href="./detail.html">Post 1</a></li>
                    <li><a href="./detail.html">Post 2</a></li>
                    <li><a href="./detail.html">Post 3</a></li>
                  </ul>
                </div>
              </div>
            </div>
        </div>
    </div>
{%endblock%}
   

myapp/blog/templates/blog/includes/footer.html
<footer class="bg-dark text-light p-3">
    <div class="col-4 d-flex justify-content-center align-items-center">
      <span class="text-light">© 2021 Company, Inc</span>
    </div>
</footer>

myapp/blog/templates/blog/includes/header.html
    <header class="p-3 bg-dark text-white">
        <div class="row">
            <div class="col">
                <h3>Blog</h3>
            </div>
            <div class="col">
                <div class="d-flex justify-content-center gap-3">
                    <a class="text-light text-decoration-none" href="">Home</a>
                    <a class="text-light text-decoration-none" href="">About</a>
                    <a class="text-light text-decoration-none" href="">Contact</a>
                </div>
            </div>
        </div>
    </header>

myapp/blog/templates/blog/index.html
{%extends 'blog/base.html'%}
{%block content%}
<div class="container-fluid ">
    <div class="row my-2">
        <div class="col">
            <h2 >{{blog_title}}</h2>
        </div>
        <div class="col-3">
            <div class="input-group">
                <input type="text" class="form-control" placeholder="Search..." aria-label="Search">
                <button class="btn btn-outline-light btn-primary " type="button" id="button-search">
                  <i class="bi bi-search"></i> <!-- Bootstrap Icons -->
                </button>
              </div>
        </div>
    </div>
    <div class="row m-3">
        {%if posts%}
            {%for post in posts%}
                <div class="col-4 mb-4">
                    <div class="card">
                        <div class="card-body">
                            <div class="row">
                                <div class="col-md-4">
                                    <img src="https://via.placeholder.com/300" class="img-fluid" alt="...">
                                </div>
                                <div class="col-md-8">
                                    <h5 class="card-title">{{post.title}}</h5>
                                    <p class="card-text">{{post.content}}</p>
                                    <div class="d-flex justify-content-between">
                                        <a href="{%url 'blog:detail' post_id=post.id%}">Read More</a>
                                        <a class="text-decoration-none text-dark fw-bold" href="#">Sports</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            {%endfor%}
        {%else%}
        <h3>No Posts Available here</h3>
        {%endif%}
        <div class="col-12 my-3">
            <nav aria-label="Page navigation">
                <ul class="pagination">
                    <li class="page-item">
                        <a class="page-link" href="?page=1" aria-label="First">
                            <span aria-hidden="true">&laquo; first</span>
                        </a>
                    </li>
                    <li class="page-item">
                        <a class="page-link" href="?page=1" aria-label="Previous">
                            <span aria-hidden="true">previous</span>
                        </a>
                    </li>
                    <li class="page-item"><span class="page-link">Page 3 of 20.</span></li>
                    <li class="page-item">
                        <a class="page-link" href="?page=4" aria-label="Next">
                            <span aria-hidden="true">next</span>
                        </a>
                    </li>
                    <li class="page-item">
                        <a class="page-link" href="?page=20" aria-label="Last">
                            <span aria-hidden="true">last &raquo;</span>
                        </a>
                    </li>
                </ul>
            </nav>
            
        </div>
    </div>
    <div class="row">
       
    </div>
    
</div>
{%endblock%}